version: "3"

services:
  node:
    image: node:20.0.0-alpine
    user: node
    tty: true
    stdin_open: true
    working_dir: /home/node
    ports:
      - 3000:3000
    volumes:
      - .:/home/node